# Site settings
title:          보충수업
description:    "생각보다 쉬운 보충수업"
baseurl:        ""
url:            "https://bochungclass.github.io"

# Author
author:         bochungclass
  name:         simhochoel
  url:          https://bochungclass.github.io
  email:        hoc6334@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
